### ISSUE TITLE
Cannot edit payment method.

### ISSUE THREAD

**Issue by jeswincyriac** [ppl-ai/api-discussion#22]
When I click edit payment button, the page goes blank after waiting for about 20 secs

![Screenshot 2024-09-05 at 11 06 44 AM](https://github.com/user-attachments/assets/3c22c5f8-0d4f-48dd-a395-a9a5f165e2fe)
![Screenshot 2024-09-05 at 11 07 00 AM](https://github.com/user-attachments/assets/e018a9c2-a29d-4f28-869f-0bd5e9522581)

**Comment by aarashy** [comment]
Hi, I think there was an issue in the frontend yesterday but this should be resolved
