### ISSUE TITLE
Payment method doesn't work in India

### ISSUE THREAD

**Issue by jeswincyriac** [ppl-ai/api-discussion#23]
As per RBI (Indian govt institution to set banking rules in India) guidelines, you cannot accept a payment without an OTP or confirmation from the customer. When I try to add credits, I get the following message from my bank.

`Sorry, we declined your txn of USD  3.00 at Www.perplexity.ai as this txn is not in accordance with the latest guideline by RBI for recurring payments. Please reach out to the merchant to update your payment preference to enjoy the services-Team OneCard`

I think payments through link (by stripe) usually goes through. Also never faced any issues opaying to openai. Can you plese check this and do the needful, so we can use the API.

**Comment by aarashy** [comment]
Hey, when you purchase credits with an indian credit card, you will get an email in your inbox explaining that the payment failed, and you will have 10 minutes to actually validate the payment.
