### ISSUE TITLE
How to Obtain Bearer Token and Additional Usage Examples for Perplexity API

### ISSUE THREAD

**Issue by Bhornumnard** [ppl-ai/api-discussion#56]
[API Reference](https://docs.perplexity.ai/api-reference/chat-completions)

I noticed that the Perplexity API Reference page only lists one route for calling the Chat Completions API. However, there is a mention of a Bearer token in the headers, but there is no information or sample on how to obtain this token for use in the Chat Completions requests.

Could you provide guidance on how to retrieve the token, and perhaps share additional examples demonstrating the usage of the Perplexity API?

**Comment by aarashy** [comment]
Hey, check https://docs.perplexity.ai/guides/getting-started
